#!/bin/sh

date
export PS4=' $SECONDS + '
set -x

export DATA=${DATAROOT:?}/${jobid:?}
mkdir -p $DATA
cd $DATA

export SENDECF=${SENDECF:-YES}

####################################
# Define execution areas
####################################
export PARMcleanup=${HOMEcleanup:?}/parm

#########################################
# Set Variable to Control Cleanup
#########################################
export cleanup_com=${cleanup_com:-"YES"}

export clean_envir=$envir

export MAXTIME=1200
#########################################
# Run setpdy and initialize PDY variables
#########################################
export cycle=t${cyc}z

setpdy.sh
. ./PDY

env

# Set which site(s) to clean up:
export SITELIST=${SITELIST:-"ncorzdm.ncep.noaa.gov ncorzdm-bldr.ncep.noaa.gov"}

#############################################################
# execute the script
if [ $envir != para ]; then
  ${HOMEcleanup}/scripts/exrzdm_cleanup.sh
else
  for  cenvir in para eval
  do
    export clean_envir=$cenvir
    ${HOMEcleanup}/scripts/exrzdm_cleanup.sh
  done
fi
export err=$?; err_chk
#############################################################

if [ "${KEEPDATA^^}" != "YES" ]; then
  rm -rf $DATA
fi
